name    'paschdan-typo3'
version '1.0.0'
author  'Daniel Paschke'
license 'Apache2'
source  'https://github.com/paschdan/puppet-typo3'
summary 'Puppet module for installing typo3'
description 'This modules installs typo3.'
dependency 'example42/puppi', '>= 2.0.0'
